### PR TITLE
Basic support for web using html2canvas

### LINKED ISSUE #224: [feature-request] Support web
Currently, it seems like react-native-view-shot just returns `undefined` when ran in a web browser with react-native-web

I understand why this happens, but it might be interesting to wrap a library like [html2canvas](http://html2canvas.hertzen.com/) to provide at least some basic functionality

I will happily send a pull request if @gre thinks that it's within the scope of the package

### PR DESCRIPTION
**Pull request by NiciusB**
Fixes #224 
It only adds partial support for captureRef (no tmpfiles). The ViewShot component might work, but I haven't tested it.

I had to add dependencies to the example (webpack and others) to get the web version working.
I also had to update the flow configs for the main package, since they were pretty old.

I've only been working with React and React Native for a couple of months, so I might have broken something. I have tested it on my own project on Android and web, and it seems to work well, but maybe the changes to the configs could break other's people projects?

### CODE REVIEW

**Comment by gre** [comment]
I'm sorry you had to fight with `example` project which was running on an old codebase/RN version. I've just completely rewrote `example` from scratch and upgraded to use latest React Native so that's why this PR have many conflicts,
would you like to backport your code into the latest master?
Thanks

**Comment by NiciusB** [comment]
I've just updated the PR.

This time there are many less changes. I'll list a couple of them, but ask if you need context for any other.

- Changed the `react-native-view-shot` dependency version on the examples folder from "^3.0.2" to "../". This allows to update the code and instantly see the results
- Added webpack and react-native-web to the examples folder to test it on the web. To run it, just do `yarn run web` and go to the listed address
- Added a `Image` test to have a very simple test and verify that the basics work
- Upped semver version of the package from "3.0.2" to "3.1.0" since this is a new feature

**Comment by jjg77** [comment]
Is this working for web now?

**Comment by NiciusB** [comment]
It doesn't seem like it's going ti get merged anytime soon. I created an npm package to use my fork in my projects: https://www.npmjs.com/package/react-native-view-shot-with-web-support

As I've found out, html2canvas isn't perfect and you might get glitchs in the image, but it's still better than nothing and can work if you don't go crazy with styling

**Comment by gre** [comment]
Unfortunately this diverged quite a bit since the PR time, sorry for my delay. I'm afraid I'll have to close it for now, but if you manage to get it updated this work can be taken in 🙏

**Pull request closed without merging**
