### PR TITLE
Android performance improvements

### PR DESCRIPTION
**Pull request by OleksandrKucherenko**
Greatly improved screenshot performance for Android platform.

### CODE REVIEW

**Comment by OleksandrKucherenko** [comment]
please review @gre

**Comment by gre** [comment]
thanks for the PR. could `example/android/gradle/wrapper/gradle-wrapper.jar`  be not committed? thanks

**Comment by OleksandrKucherenko** [comment]
That's a gradle wrapper - it used for downloading required gradle components (~112Mb) and starting the build process. Yes, its possible to run without it, but that require specially configured environment, which most devs don't have.  

So you have two choices:
- keep gradle wrapper in the project and have the ability to run all only if jdk/jre available OR
- demand from devs to spend extra efforts for configuring the project

most projects prefer to stay with the first option, as easiest for maintenance.

**Comment by gre** [comment]
make sense!

**Comment by gre** [comment]
thanks for this feature! i'll test & do a new release

**Comment by OleksandrKucherenko** [comment]
thats a gradle issue, try to run build after those commands:

> # stop all instances of gradle daemons, for reducing risks of clash
> ./gradlew --stop
> # ask gradle to clean project from temporary build results and caches
> ./gradlew clean cleanBuildCache

after that, you can execute compilation again in Android Studio or from the command line.

> ./gradlew assembleDebug

**Comment by OleksandrKucherenko** [comment]
@gre now it builds without any problems, please check and confirm merge.

P.S. We use this project in visual testing. And it is used quite heavily in the production cycle, mostly 100 pull requests that we have in the current moment in own repository will benefit from those changes. Our visual tests got boost ~30% during tests execution just due to those changes.

**Comment by gre** [comment]
👍  thanks for the changes, i'll probably only have time to review it next weekend.

**Comment by OleksandrKucherenko** [comment]
@gre added the fix that resolves issues with wrong positioning of childs-views on the final screenshot.

**Comment by gre** [comment]
neat! I have no idea why but i still can't run the example. in the meantime, I'll merge this and publish & try to run it again later.

**Comment by gre** [comment]
thanks alot for the PR

**Pull request merged**
