### PR TITLE
add custom file name props for android

### PR DESCRIPTION
**Pull request by LkyYuen**

### CODE REVIEW

**Comment by m4yer** [comment]
Would be really nice to have this one!

**Comment by gre** [comment]
May I know the reason why you would want to give a name to that file? It's meant to be a temporary file that you later can reuse to send to a server / send to the user as a "share" action / ...

**Comment by m4yer** [comment]
> May I know the reason why you would want to give a name to that file? It's meant to be a temporary file that you later can reuse to send to a server / send to the user as a "share" action / ...

For me the reason is the ability of downloading this file and it does not look good when the filename is something like "react-native......" in user's gallery.

**Comment by gre** [comment]
I didn't know this file would appear at all in user's phone? I thought the current folder used was invisible for the user.
The goal was always that this file is a temporary file and when you need to show that file to user, you would need to use a library like `react-native-fs` to move the file to a more permanent place and with a better file name.

This is specifically documented in https://github.com/gre/react-native-view-shot#saving-to-a-file

Overall i'm not sure if this is a good idea to put this in this library, it feels out of scope to me. but still open to discussion if there is no other workaround.

**Comment by juniorklawa** [comment]
In my case it would be nice to have the option to rename the file because I use this ViewShot to share on social networks like Instagram and WhatsApp and a name like ReactNative-snapshot is not so elegant, since before sharing an image her name appears above the sharing options and in this case the image is temporary.
[Example](https://imgur.com/a/Wnzpz6c)

**Comment by CanRau** [comment]
Also renaming would allow be to save it straight to `MediaLibrary` without the need need to [copy], move to rename and then save to media library
Though would appreciate that option for iOS as well
Till then I'm using the work around, just wanted to share my use case and thanks a lot for this package by the way 🙏

**Review by gre — APPROVED** [review]

**Comment by gre** [comment]
Thanks for the PR.

**Pull request merged**
