### PR TITLE
android: capture view blank fix

### PR DESCRIPTION
**Pull request by helpkang**

### CODE REVIEW

**Comment by gre** [comment]
Hi,
can you explain what this fixes?

Does this fix https://github.com/gre/react-native-view-shot/issues/14 ? (because I think we should probably just remove the `.layout` line)

If it does not fixes #14, please provide a test-case that reproduce the problem because I didn't found a problem with Canvas so far.
The problem with `view.getDrawingCache()` is it fails with big views. I actually recently switched to Canvas because of this limitation: https://github.com/gre/react-native-view-shot/issues/13 . But maybe there is a case Canvas doesn't work, do you have a way to reproduce this? In that case, we need to figure out if we need a parameter to select one or the other capture technique.

Thanks

**Comment by helpkang** [comment]
Hi,

Gaëtan Renaudeau.

sorry not recognize #13.

this change my android device is working.

Thanks .




2016-10-07 16:23 GMT+09:00 Gaëtan Renaudeau <notifications@github.com>:

**Comment by gre** [comment]
could you update the PR with a fix? thanks :)

**Comment by gre** [comment]
released v1.5.0 with a fix

**Pull request closed without merging**
