### PR TITLE
recursively create folders before creating file

### PR DESCRIPTION
**Pull request by shahen94**
### Motivation

I found that we can't use nested paths on android to saving snapshots. So this PR added ability to recursively create folders before taking snapshot.

### Test Plan.

This don't tested, needed to test.

### CODE REVIEW

**Comment by gre** [comment]
I'm sorry but I actually plan to drop the "path" feature. see https://github.com/gre/react-native-view-shot/issues/67
the library needs to focus more on snapshotting a view, any aspect regarding files, permissions, intents to save at some spaces, can be solved in a separate module.

like `viewshot.capture(..).then(tmpFileUri => FS.move(tmpFileUri, somewhere))`

**Comment by shahen94** [comment]
@gre thanks for so quick reply. Anyway path is working on iOS normally, but throws error on android. So this PR looks like bugfix.

**Comment by gre** [comment]
yeah I guess i can accept it and will plan for future deprecation of `path` .

thanks :)

**Comment by shahen94** [comment]
@gre thanks so much !

**Pull request merged**
