### PR TITLE
Update RNViewShot.m

### PR DESCRIPTION
**Pull request by jiushicheng**
bug fixed: ios ScreenShot

### CODE REVIEW

**Comment by gre** [comment]
so  `[view.layer renderInContext:UIGraphicsGetCurrentContext()];` is doing something that `success = [rendered drawViewHierarchyInRect:(CGRect){CGPointZero, size} afterScreenUpdates:YES];` is not doing? maybe the issue is the rect size?

I think we will have to do one or the other, but not sure if going renderInContext won't have another issue (I remember this topic is tricky because there are case one or the other don't work)

does the problem occur when are you snapshotting a ScrollView or a normal View?

**Comment by jiushicheng** [comment]
the problem occur when snapshotting a ScrollView ,but l use the high level Api 

At 2017-11-03 17:43:27, "Gaëtan Renaudeau" <notifications@github.com> wrote:


so [view.layer renderInContext:UIGraphicsGetCurrentContext()]; is doing something that success = [rendered drawViewHierarchyInRect:(CGRect){CGPointZero, size} afterScreenUpdates:YES]; is not doing? maybe the issue is the rect size?

I think we will have to do one or the other, but not sure if going renderInContext won't have another issue (I remember this topic is tricky because there are case one or the other don't work)

does the problem occur when are you snapshotting a ScrollView or a normal View?

**Comment by gre** [comment]
the fact the code is doing twice the same thing (rendering the view) does not feel the fix is correct. This PR need more explanation if it actually make a difference.

**Comment by Mitesh-2009** [comment]
[rendered.layer renderInContext:UIGraphicsGetCurrentContext()]; not working to capture scrollview contents

**Comment by jefflewis** [comment]
When using `renderInContext` in my app, I capture a > 8000 point scrollview with no issues. `drawViewHierarchyInRect` fails with an empty image.

**Comment by awadeyar** [comment]
Any update on this?
 as _**renderInContext**_ does the trick why can't you update the library?

**Pull request closed without merging**
