### PR TITLE
Add possibility to capture SurfaceView content

### PR DESCRIPTION
**Pull request by CAMOBAP**
- https://github.com/gre/react-native-view-shot/issues/320

Feedback need

### CODE REVIEW

**Comment by K12AZ** [comment]
@CAMOBAP Thank you and really appreciated. I will check and let you know.

**Comment by gre** [comment]
Any help on testing this is appreciated. I'll give a try on my end.

**Comment by gre** [comment]
I didn't had time yet to test this. Do you know how I can test it by the way? I don't remember if our /example covers it.

**Comment by CAMOBAP** [comment]
> Do you know how I can test it by the way?

GLSurfaceView need to be inside View, IDK how to add it in ReactNative, I created it in native code

> I don't remember if our /example covers it.

Looks like no

**Comment by gre** [comment]
To be able to merge this, we need to have an example added that can allow us to test it and confirm all works. I have just refreshed the project example/Example with latest bootstrap of react native and libraries. Do you think you would be able to add an example? thanks

**Comment by CAMOBAP** [comment]
> To be able to merge this, we need to have an example added that can allow us to test it and confirm all works. I have just refreshed the project example/Example with latest bootstrap of react native and libraries. Do you think you would be able to add an example? thanks

Yep, I hope I will have some time to add Example in next two weeks

**Comment by jhen0409** [comment]
I tested this PR, and found some issues and trying to fix that.

- Use the default handler of `PixelCopy.request` with CountDownLatch seems like block something, I waited the full 5 seconds to get the screenshot.
  - I changed to use `Looper.getMainLooper()` gets more smooth
- Just `PixelCopy.request` to main bitmap will directly fill the main bitmap, it's not in the right place
  - I created a new bitmap and draw to the canvas with the child view position

<details>
<summary>Click to expand the patch code</summary>

```patch
diff --git a/node_modules/react-native-view-shot/android/src/main/java/fr/greweb/reactnativeviewshot/ViewShot.java b/node_modules/react-native-view-shot/android/src/main/java/fr/greweb/reactnativeviewshot/ViewShot.java
index 16589b6..ab212d3 100644
--- a/node_modules/react-native-view-shot/android/src/main/java/fr/greweb/reactnativeviewshot/ViewShot.java
+++ b/node_modules/react-native-view-shot/android/src/main/java/fr/greweb/reactnativeviewshot/ViewShot.java
@@ -8,6 +8,8 @@ import android.graphics.Matrix;
 import android.graphics.Paint;
 import android.graphics.Point;
 import android.net.Uri;
+import android.os.Build;
+import android.os.Handler;
 
 import androidx.annotation.IntDef;
 import androidx.annotation.NonNull;
@@ -16,8 +18,11 @@ import androidx.annotation.StringDef;
 import android.os.Build;
 import android.os.Handler;
 import android.os.HandlerThread;
+import android.os.Looper;
 import android.util.Base64;
 import android.util.Log;
+import android.view.PixelCopy;
+import android.view.SurfaceView;
 import android.view.TextureView;
 import android.view.View;
 import android.view.ViewGroup;
@@ -44,6 +49,8 @@ import java.util.List;
 import java.util.Locale;
 import java.util.Set;
 import java.util.WeakHashMap;
+import java.util.concurrent.CountDownLatch;
+import java.util.concurrent.TimeUnit;
 import java.util.zip.Deflater;
 
 import javax.annotation.Nullable;
@@ -72,6 +79,8 @@ public class ViewShot implements UIBlock, LifecycleEventListener {
      */
     private static final int ARGB_SIZE = 4;
 
+    private static final int SURFACE_VIEW_READ_PIXELS_TIMEOUT = 5;
+
     private HandlerThread mBgThread;
     private Handler mBgHandler;
 
@@ -157,6 +166,7 @@ public class ViewShot implements UIBlock, LifecycleEventListener {
     private final Boolean snapshotContentContainer;
     @SuppressWarnings({"unused", "FieldCanBeLocal"})
     private final ReactApplicationContext reactContext;
+    private final boolean handleGLSurfaceView;
     private final Activity currentActivity;
     //endregion
 
@@ -174,6 +184,7 @@ public class ViewShot implements UIBlock, LifecycleEventListener {
             final Boolean snapshotContentContainer,
             final ReactApplicationContext reactContext,
             final Activity currentActivity,
+            final boolean handleGLSurfaceView,
             final Promise promise) {
         this.tag = tag;
         this.extension = extension;
@@ -186,6 +197,7 @@ public class ViewShot implements UIBlock, LifecycleEventListener {
         this.snapshotContentContainer = snapshotContentContainer;
         this.reactContext = reactContext;
         this.currentActivity = currentActivity;
+        this.handleGLSurfaceView = handleGLSurfaceView;
         this.promise = promise;
 
         reactContext.addLifecycleEventListener(this);
@@ -403,28 +415,60 @@ public class ViewShot implements UIBlock, LifecycleEventListener {
         //after view is drawn, go through children
         final List<View> childrenList = getAllChildren(view);
 
+        int[] point = new int[2];
+        view.getLocationInWindow(point);
+        final int rootX = point[0];
+        final int rootY = point[1];
+
         for (final View child : childrenList) {
             // skip any child that we don't know how to process
-            if (!(child instanceof TextureView)) continue;
-
-            // skip all invisible to user child views
-            if (child.getVisibility() != VISIBLE) continue;
-
-            final TextureView tvChild = (TextureView) child;
-            tvChild.setOpaque(false); // <-- switch off background fill
-
-            // NOTE (olku): get re-usable bitmap. TextureView should use bitmaps with matching size,
-            // otherwise content of the TextureView will be scaled to provided bitmap dimensions
-            final Bitmap childBitmapBuffer = tvChild.getBitmap(getExactBitmapForScreenshot(child.getWidth(), child.getHeight()));
-
-            final int countCanvasSave = c.save();
-            applyTransformations(c, view, child);
-
-            // due to re-use of bitmaps for screenshot, we can get bitmap that is bigger in size than requested
-            c.drawBitmap(childBitmapBuffer, 0, 0, paint);
-
-            c.restoreToCount(countCanvasSave);
-            recycleBitmap(childBitmapBuffer);
+            if (child instanceof TextureView) {
+                // skip all invisible to user child views
+                if (child.getVisibility() != VISIBLE) continue;
+
+                final TextureView tvChild = (TextureView) child;
+                tvChild.setOpaque(false); // <-- switch off background fill
+
+                // NOTE (olku): get re-usable bitmap. TextureView should use bitmaps with matching size,
+                // otherwise content of the TextureView will be scaled to provided bitmap dimensions
+                final Bitmap childBitmapBuffer = tvChild.getBitmap(getExactBitmapForScreenshot(child.getWidth(), child.getHeight()));
+
+                final int countCanvasSave = c.save();
+                applyTransformations(c, view, child);
+
+                // due to re-use of bitmaps for screenshot, we can get bitmap that is bigger in size than requested
+                c.drawBitmap(childBitmapBuffer, 0, 0, paint);
+
+                c.restoreToCount(countCanvasSave);
+                recycleBitmap(childBitmapBuffer);
+            } else if (child instanceof SurfaceView && handleGLSurfaceView) {
+                final SurfaceView svChild = (SurfaceView)child;
+                final CountDownLatch latch = new CountDownLatch(1);
+
+                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
+                    final Bitmap childBitmapBuffer = getExactBitmapForScreenshot(child.getWidth(), child.getHeight());
+                    try {
+                        PixelCopy.request(svChild, childBitmapBuffer, new PixelCopy.OnPixelCopyFinishedListener() {
+                            @Override
+                            public void onPixelCopyFinished(int copyResult) {
+                                int[] childPoint = new int[2];
+                                svChild.getLocationInWindow(childPoint);
+                                c.drawBitmap(childBitmapBuffer, childPoint[0] - rootX, childPoint[1] - rootY, paint);
+                                recycleBitmap(childBitmapBuffer);
+                                latch.countDown();
+                            }
+                        }, new Handler(Looper.getMainLooper()));
+                        latch.await(SURFACE_VIEW_READ_PIXELS_TIMEOUT, TimeUnit.SECONDS);
+                    } catch (Exception e) {
+                        Log.e(TAG, "Cannot PixelCopy for " + svChild, e);
+                    }
+                } else {
+                    Bitmap cache = svChild.getDrawingCache();
+                    if (cache != null) {
+                        c.drawBitmap(svChild.getDrawingCache(), 0, 0, paint);
+                    }
+                }
+            }
         }
 
         if (width != null && height != null && (width != w || height != h)) {

```
</details>

**Comment by CAMOBAP** [comment]
@jhen0409 good improvements, unfortunatelly I lost access to original repo, may I kindly ask you to create a new PR in favor of this one. Also if you can add some examples that would be nice. I closing this one

**Pull request closed without merging**
